'ELECTRO-FILTRE'; 
'REACTEUR SEMI HUMIDE'; 
'LAVAGE, REGULATION'; 
'FILTRE A MANCHES'; 
'ECONOMISEUR'; 
'TOUR DE REFROIDISSEMENT'; 
'QUENCH'; 
'G1'; 
'SL1'; 
'G2'; 
'SL2'; 
'MAF'; 
'MEF'; 
'G3'; 
'SL3'; 
'ECH SOUS REFROIDISSEMENT 1'; 
'ECH SOUS REFROIDISSEMENT 2'; 
'OXYDATION';
'CYCLONE'; 
'VENTILATEUR RECIRCULATION'; 
'DESATURATEUR'; 
'RECUPERATEUR'; 
'réchauffage SCR'; 
'SCR'; 
'YT1'; 
'YT2'; 
'Réchauffeur final'; 
'CHEMINEE'; 
'Stockage CaO'; 
'Stockage Ca(OH)₂'; 
'Stockage Charbon actif / HOK'; 
'Stockage NaHCO₃'; 
'Stockage autre réactif solide'; 
'Stockage NaOH'; 
'Injection NH₃';
'OH'; 
'Stockage Urée'; 
'Stockage PREFIOM'; 
'TP mécanique'; 
'TP pneumatique'; 
'Humidification des résidus'; 
'YAPOLAB'; 
'ACTILAB'; 
'DISTRICT HEATING / HEAT RECOVERY'; 
'STATION Chaux CaO'; 
'STATION Chaux Ca(OH)₂'; 
'STATION Charbon Actif / HOK'; 
'STATION Soude'; 
'STATION Lait de Calcaire';